services:
  - type: web
    name: budgetbuddy-chatbot
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        generateValue: true
